import {
  Loader2,
  LucideProps,
  Moon,
  Sun,
  Github,
  Twitter,
  Linkedin,
  Mail,
  Phone,
  MapPin,
  Globe,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  X,
  Menu,
  Search,
  Filter,
  Download,
  Upload,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  User,
  Users,
  Calendar,
  Clock,
  Check,
  AlertCircle,
  Info,
  Star,
  Heart,
  Share,
  Bookmark,
  Edit,
  Trash,
  Copy,
  MoreVertical,
  Settings,
  HelpCircle,
  LogOut,
  Home,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  CreditCard,
  ShoppingCart,
  Package,
  Truck,
  Building,
  Briefcase,
  Award,
  Target,
  Zap,
  Shield,
  Key,
  Bell,
  MessageSquare,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  sun: Sun,
  moon: Moon,
  google: ({ ...props }: LucideProps) => (
    <svg role="img" viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
      />
    </svg>
  ),
  github: Github,
  twitter: Twitter,
  linkedin: Linkedin,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  globe: Globe,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  x: X,
  menu: Menu,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  user: User,
  users: Users,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  alertCircle: AlertCircle,
  info: Info,
  star: Star,
  heart: Heart,
  share: Share,
  bookmark: Bookmark,
  edit: Edit,
  trash: Trash,
  copy: Copy,
  moreVertical: MoreVertical,
  settings: Settings,
  helpCircle: HelpCircle,
  logout: LogOut,
  home: Home,
  barChart: BarChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  dollarSign: DollarSign,
  creditCard: CreditCard,
  shoppingCart: ShoppingCart,
  package: Package,
  truck: Truck,
  building: Building,
  briefcase: Briefcase,
  award: Award,
  target: Target,
  zap: Zap,
  shield: Shield,
  key: Key,
  bell: Bell,
  messageSquare: MessageSquare,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,
}